name: Student CI CD

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Download source code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install pytest
        run: pip install pytest

      - name: Run automated tests
        run: pytest -v

  deploy:
    name: Deploy Website
    needs: test
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download source code
        uses: actions/checkout@v5

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload website
        uses: actions/upload-pages-artifact@v4
        with:
          path: .

      - name: Deploy website
        id: deployment
        uses: actions/deploy-pages@v4
